### ISSUE TITLE
"Guy in Settlement is inspired and wants money" triggers without any settlements

### ISSUE THREAD

**Issue by Pingger** [Pingger/Empire-Mod#3]

**Comment by RadsuitRandy** [comment]
This isn't necessarily a bug. This has been in the mod ever since this event existed, and so I don't know if Saakra intended it to work like this anyway. However, it would make sense to fix it so you can't have that event unless you have a settlement.

**Comment by Pingger** [comment]
At least the text needs to be rewritten, since it states, that the guy is in one of my settlements ...

**Comment by FalconElaris** [comment]
Recommendation: "A smith of a nearby settlement has received a great inspiration and is seeking patrons for what he claims will be a work of unparalleled quality! He plans to give it to his patron as a token of his loyalty." 
Use this to obfuscate the origin of the smith.

**Comment by Pingger** [comment]
Good idea, has been implemented
