### ISSUE TITLE
Trait "Deep defense" doesn't seem to work

### ISSUE THREAD

**Issue by Pingger** [Pingger/Empire-Mod#9]

**Comment by FalconElaris** [comment]
What is broken about it? Should the Military level be 2 by default with Defense in Depth? Currently, my settlement with a barracks is only a Mil level of 1.

**Comment by FalconElaris** [comment]
However, when I selected "Set Defending Force", it says the value is 3; so, while the mil level is only 1 the defense value is 3. 
![Defense_in_depth_on_raid_set_defense_force_value](https://user-images.githubusercontent.com/3372722/128597815-dc7e9cad-43f6-44ad-8751-313a6a676f7d.PNG)
